method_request: POST _ml/trained_models/my_model_for_search/deployment/_stop
alternatives:
  - language: Python
    code: |-
      resp = client.ml.stop_trained_model_deployment(
          model_id="my_model_for_search",
      )
  - language: JavaScript
    code: |-
      const response = await client.ml.stopTrainedModelDeployment({
        model_id: "my_model_for_search",
      });
  - language: Ruby
    code: |-
      response = client.ml.stop_trained_model_deployment(
        model_id: "my_model_for_search"
      )
  - language: PHP
    code: |-
      $resp = $client->ml()->stopTrainedModelDeployment([
          "model_id" => "my_model_for_search",
      ]);
  - language: curl
    code: 'curl -X POST -H "Authorization: ApiKey $ELASTIC_API_KEY"
      "http://localhost:9200/_ml/trained_models/my_model_for_search/deployment/_stop"'
