method_request: POST _tasks/<task_id>/_cancel
alternatives:
  - language: Python
    code: |-
      resp = client.tasks.cancel(
          task_id="<task_id>",
      )
  - language: JavaScript
    code: |-
      const response = await client.tasks.cancel({
        task_id: "<task_id>",
      });
  - language: Ruby
    code: |-
      response = client.tasks.cancel(
        task_id: "<task_id>"
      )
  - language: PHP
    code: |-
      $resp = $client->tasks()->cancel([
          "task_id" => "<task_id>",
      ]);
  - language: curl
    code: 'curl -X POST -H "Authorization: ApiKey $ELASTIC_API_KEY" "http://localhost:9200/_tasks/<task_id>/_cancel"'
