summary: Get cluster actions
description: >
  A successful response from `GET _tasks?actions=cluster:*`, which retrieves all cluster-related tasks.
# type: response
# response_code: ''
value: |-
  {
    "nodes" : {
      "oTUltX4IQMOUUVeiohTt8A" : {
        "name" : "H5dfFeA",
        "transport_address" : "127.0.0.1:9300",
        "host" : "127.0.0.1",
        "ip" : "127.0.0.1:9300",
        "tasks" : {
          "oTUltX4IQMOUUVeiohTt8A:124" : {
            "node" : "oTUltX4IQMOUUVeiohTt8A",
            "id" : 124,
            "type" : "direct",
            "action" : "cluster:monitor/tasks/lists[n]",
            "start_time_in_millis" : 1458585884904,
            "running_time_in_nanos" : 47402,
            "cancellable" : false,
            "parent_task_id" : "oTUltX4IQMOUUVeiohTt8A:123"
          },
          "oTUltX4IQMOUUVeiohTt8A:123" : {
            "node" : "oTUltX4IQMOUUVeiohTt8A",
            "id" : 123,
            "type" : "transport",
            "action" : "cluster:monitor/tasks/lists",
            "start_time_in_millis" : 1458585884904,
            "running_time_in_nanos" : 236042,
            "cancellable" : false
          }
        }
      }
    }
  }
