method_request: GET _application/search_application?from=0&size=3&q=app*
alternatives:
  - language: Python
    code: |-
      resp = client.search_application.list(
          from="0",
          size="3",
          q="app*",
      )
  - language: JavaScript
    code: |-
      const response = await client.searchApplication.list({
        from: 0,
        size: 3,
        q: "app*",
      });
  - language: Ruby
    code: |-
      response = client.search_application.list(
        from: "0",
        size: "3",
        q: "app*"
      )
  - language: PHP
    code: |-
      $resp = $client->searchApplication()->list([
          "from" => "0",
          "size" => "3",
          "q" => "app*",
      ]);
  - language: curl
    code: 'curl -X GET -H "Authorization: ApiKey $ELASTIC_API_KEY"
      "http://localhost:9200/_application/search_application?from=0&size=3&q=app*"'
