method_request: POST _ml/trained_models/elastic__distilbert-base-uncased-finetuned-conll03-english/deployment/_update
description: An example body for a `POST
  _ml/trained_models/elastic__distilbert-base-uncased-finetuned-conll03-english/deployment/_update` request.
value: |-
  {
    "number_of_allocations": 4
  }
alternatives:
  - language: Python
    code: |-
      resp = client.ml.update_trained_model_deployment(
          model_id="elastic__distilbert-base-uncased-finetuned-conll03-english",
          number_of_allocations=4,
      )
  - language: JavaScript
    code: |-
      const response = await client.ml.updateTrainedModelDeployment({
        model_id: "elastic__distilbert-base-uncased-finetuned-conll03-english",
        number_of_allocations: 4,
      });
  - language: Ruby
    code: |-
      response = client.ml.update_trained_model_deployment(
        model_id: "elastic__distilbert-base-uncased-finetuned-conll03-english",
        body: {
          "number_of_allocations": 4
        }
      )
  - language: PHP
    code: |-
      $resp = $client->ml()->updateTrainedModelDeployment([
          "model_id" => "elastic__distilbert-base-uncased-finetuned-conll03-english",
          "body" => [
              "number_of_allocations" => 4,
          ],
      ]);
  - language: curl
    code:
      'curl -X POST -H "Authorization: ApiKey $ELASTIC_API_KEY" -H "Content-Type: application/json" -d
      ''{"number_of_allocations":4}''
      "$ELASTICSEARCH_URL/_ml/trained_models/elastic__distilbert-base-uncased-finetuned-conll03-english/deployment/_update"'
alternative_java:
  - language: java
    code: |
      client.ml().updateTrainedModelDeployment(u -> u
      	.modelId("elastic__distilbert-base-uncased-finetuned-conll03-english")
      	.numberOfAllocations(4)
      );
