method_request: POST _ml/trained_models/elastic__distilbert-base-uncased-finetuned-conll03-english/deployment/_update
description: An example body for a `POST
  _ml/trained_models/elastic__distilbert-base-uncased-finetuned-conll03-english/deployment/_update` request.
value: |-
  {
    "number_of_allocations": 4
  }
