method_request: GET _cat/tasks?v=true&format=json
alternatives:
  - language: Python
    code: |-
      resp = client.cat.tasks(
          v=True,
          format="json",
      )
  - language: JavaScript
    code: |-
      const response = await client.cat.tasks({
        v: "true",
        format: "json",
      });
  - language: Ruby
    code: |-
      response = client.cat.tasks(
        v: "true",
        format: "json"
      )
  - language: PHP
    code: |-
      $resp = $client->cat()->tasks([
          "v" => "true",
          "format" => "json",
      ]);
  - language: curl
    code: 'curl -X GET -H "Authorization: ApiKey $ELASTIC_API_KEY" "$ELASTICSEARCH_URL/_cat/tasks?v=true&format=json"'
  - language: java
    code: |
      client.cat().tasks();
