summary: Reset an index setting
method_request: PUT /my-index-000001/_settings
description: To revert a setting to the default value, use `null`.
# type: request
value: "{

  \  \"index\" : {

  \    \"refresh_interval\" : null

  \  }

  }"
alternatives:
  - language: Python
    code: |-
      resp = client.indices.put_settings(
          index="my-index-000001",
          settings={
              "index": {
                  "refresh_interval": None
              }
          },
      )
  - language: JavaScript
    code: |-
      const response = await client.indices.putSettings({
        index: "my-index-000001",
        settings: {
          index: {
            refresh_interval: null,
          },
        },
      });
  - language: Ruby
    code: |-
      response = client.indices.put_settings(
        index: "my-index-000001",
        body: {
          "index": {
            "refresh_interval": nil
          }
        }
      )
  - language: PHP
    code: |-
      $resp = $client->indices()->putSettings([
          "index" => "my-index-000001",
          "body" => [
              "index" => [
                  "refresh_interval" => null,
              ],
          ],
      ]);
  - language: curl
    code:
      'curl -X PUT -H "Authorization: ApiKey $ELASTIC_API_KEY" -H "Content-Type: application/json" -d
      ''{"index":{"refresh_interval":null}}'' "http://localhost:9200/my-index-000001/_settings"'
