# summary: connector/apis/update-connector-configuration-api.asciidoc:308
method_request: PUT _connector/my-spo-connector/_configuration
# description: ''
# type: request
value: "{

  \    \"values\": {

  \        \"tenant_id\": \"my-tenant-id\",

  \        \"tenant_name\": \"my-sharepoint-site\",

  \        \"client_id\": \"foo\",

  \        \"secret_value\": \"bar\",

  \        \"site_collections\": \"*\"

  \    }

  }"
alternatives:
  - language: Python
    code: |-
      resp = client.connector.update_configuration(
          connector_id="my-spo-connector",
          values={
              "tenant_id": "my-tenant-id",
              "tenant_name": "my-sharepoint-site",
              "client_id": "foo",
              "secret_value": "bar",
              "site_collections": "*"
          },
      )
  - language: JavaScript
    code: |-
      const response = await client.connector.updateConfiguration({
        connector_id: "my-spo-connector",
        values: {
          tenant_id: "my-tenant-id",
          tenant_name: "my-sharepoint-site",
          client_id: "foo",
          secret_value: "bar",
          site_collections: "*",
        },
      });
  - language: Ruby
    code: |-
      response = client.connector.update_configuration(
        connector_id: "my-spo-connector",
        body: {
          "values": {
            "tenant_id": "my-tenant-id",
            "tenant_name": "my-sharepoint-site",
            "client_id": "foo",
            "secret_value": "bar",
            "site_collections": "*"
          }
        }
      )
  - language: PHP
    code: |-
      $resp = $client->connector()->updateConfiguration([
          "connector_id" => "my-spo-connector",
          "body" => [
              "values" => [
                  "tenant_id" => "my-tenant-id",
                  "tenant_name" => "my-sharepoint-site",
                  "client_id" => "foo",
                  "secret_value" => "bar",
                  "site_collections" => "*",
              ],
          ],
      ]);
  - language: curl
    code:
      "curl -X PUT -H \"Authorization: ApiKey $ELASTIC_API_KEY\" -H \"Content-Type: application/json\" -d
      '{\"values\":{\"tenant_id\":\"my-tenant-id\",\"tenant_name\":\"my-sharepoint-site\",\"client_id\":\"foo\",\"secret_value\":\"\
      bar\",\"site_collections\":\"*\"}}' \"$ELASTICSEARCH_URL/_connector/my-spo-connector/_configuration\""
  - language: java
    code: >
      client.connector().updateConfiguration(u -> u
      	.connectorId("my-spo-connector")
      	.values(Map.of("tenant_id", JsonData.fromJson("\"my-tenant-id\""),"tenant_name", JsonData.fromJson("\"my-sharepoint-site\""),"secret_value", JsonData.fromJson("\"bar\""),"client_id", JsonData.fromJson("\"foo\""),"site_collections", JsonData.fromJson("\"*\"")))
      );
