# summary: connector/apis/update-connector-configuration-api.asciidoc:335
method_request: PUT _connector/my-spo-connector/_configuration
# description: ''
# type: request
value: "{

  \    \"values\": {

  \        \"secret_value\": \"foo-bar\"

  \    }

  }"
